language: node_js
sudo: false
node_js:
- '0.12'

branches:
  only:
    - master
    - dev

env:
  global:

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
- npm install -g gulp
- npm install -g karma
- npm install

cache:
  directories:
  - "$HOME/.nvm"
